"""Count selected two-edge anatomical routes by input and output side."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import defaultdict
from pathlib import Path

if not __package__:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from flyai.selected_graph import OUTPUT_KEYS, SelectedGraph, load_selected_graph


INPUT_SIDES = ("left", "center", "right")


def side_route_rows(graph: SelectedGraph) -> list[dict]:
    """Count ordered photo→OCG01→output paths; never infer neural activity."""
    parents: dict[int, list[int]] = defaultdict(list)
    for edge in graph.edges:
        parents[edge.post_index].append(edge.pre_index)
    rows = []
    for role, side in OUTPUT_KEYS:
        output_index = graph.outputs[(role, side)]
        by_side: dict[str, set[int]] = {name: set() for name in INPUT_SIDES}
        paths = {name: 0 for name in INPUT_SIDES}
        fully_same_side: set[int] = set()
        fully_same_side_paths = 0
        for relay_index in parents[output_index]:
            relay = graph.nodes[relay_index]
            if relay.role != "OCG01":
                raise ValueError("Expected an OCG01 relay before each output")
            for input_index in parents[relay_index]:
                photo = graph.nodes[input_index]
                if photo.role != "photoreceptor" or photo.side not in by_side:
                    raise ValueError("Expected a side-labeled photoreceptor before OCG01")
                by_side[photo.side].add(input_index)
                paths[photo.side] += 1
                if photo.side == relay.side == side:
                    fully_same_side.add(input_index)
                    fully_same_side_paths += 1
        rows.append({
            "root_id": graph.nodes[output_index].root_id,
            "role": role,
            "side": side,
            "ordered_paths_by_input_side": paths,
            "unique_inputs_by_side": {name: len(by_side[name]) for name in INPUT_SIDES},
            "unique_inputs_total": len(set().union(*by_side.values())),
            "same_side_ordered_paths": fully_same_side_paths,
            "same_side_unique_inputs": len(fully_same_side),
        })
    return rows


def render_note(report: dict) -> str:
    lines = [
        "# Selected input-side routes to descending outputs — 2026-09-29",
        "",
        "**OBSERVATION:** Counts of ordered two-edge anatomical routes in the selected",
        "2024 FAFB v783 graph. These are paths, not neural responses or wheel commands.",
        "A photoreceptor can contribute multiple paths through different OCG01 cells;",
        "therefore the path and unique-input columns answer different questions.",
        "",
        "| Output | Input left paths | Input center paths | Input right paths | Unique inputs L/C/R | Fully same-side paths |",
        "| --- | ---: | ---: | ---: | --- | ---: |",
    ]
    for row in report["outputs"]:
        p, u = row["ordered_paths_by_input_side"], row["unique_inputs_by_side"]
        lines.append(f"| {row['role']} {row['side']} | {p['left']} | {p['center']} | "
                     f"{p['right']} | {u['left']}/{u['center']}/{u['right']} | "
                     f"{row['same_side_ordered_paths']} |")
    lines.extend([
        "",
        "**INFERENCE:** The table shows whether a proposed left/right virtual",
        "readout would mix inputs from other annotated sides. It does not establish",
        "the sign, gain, or functional effect of any route. Center inputs and",
        "cross-side routes remain present in the graph; P4 must define how to use",
        "them before any behavioral result is interpreted.",
        "",
        f"Node CSV SHA-256: `{report['nodes_csv_sha256']}`.  ",
        f"Edge CSV SHA-256: `{report['edges_csv_sha256']}`.  ",
        f"Extraction report SHA-256: `{report['extraction_report_sha256']}`.",
        "",
        "Run `.venv\\Scripts\\python.exe src\\flyai\\assess_side_routes.py --workspace .`",
        "to generate this note and `data/derived/selected_side_routes.json`; use",
        "`--verify-existing` to compare regenerated bytes without overwriting them.",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--verify-existing", action="store_true")
    args = parser.parse_args()
    root = args.workspace.resolve()
    graph = load_selected_graph(root)
    report_path = root / "data/derived/selected_subnetwork_report.json"
    archived = json.loads(report_path.read_text(encoding="utf-8"))
    rows = side_route_rows(graph)
    if len(archived["selected_outputs"]) != len(rows):
        raise ValueError("Archived selected output count changed")
    for row, old in zip(rows, sorted(archived["selected_outputs"],
                                     key=lambda item: OUTPUT_KEYS.index((item["role"], item["side"])))):
        if (row["root_id"] != old["root_id"] or
                sum(row["ordered_paths_by_input_side"].values()) != old["distinct_ordered_role_paths"] or
                row["unique_inputs_total"] != old["unique_photoreceptors"] or
                row["same_side_unique_inputs"] != old["fully_same_side_photoreceptors"]):
            raise ValueError("Side-route recount differs from archived selected output")
    result = {
        "status": "anatomical side-route audit; no neural dynamics or behavior",
        "dataset": archived["dataset"],
        "nodes_csv_sha256": graph.nodes_sha256,
        "edges_csv_sha256": graph.edges_sha256,
        "extraction_report_sha256": hashlib.sha256(report_path.read_bytes()).hexdigest(),
        "method": "count ordered photoreceptor -> OCG01 -> output triples by photoreceptor side; unique input IDs counted separately",
        "outputs": rows,
    }
    targets = {
        root / "data/derived/selected_side_routes.json": (json.dumps(result, indent=2) + "\n").encode("utf-8"),
        root / "docs/selected_side_routes.md": render_note(result).encode("utf-8"),
    }
    for path, content in targets.items():
        if args.verify_existing:
            if not path.exists() or path.read_bytes() != content:
                raise ValueError(f"Existing side-route output mismatch: {path}")
        else:
            if path.exists():
                raise FileExistsError(f"Preserve existing side-route output: {path}")
            path.write_bytes(content)
    print("PASS: 4 outputs, side-route recount matches archived graph; " +
          ("existing outputs unchanged" if args.verify_existing else "outputs written"))


if __name__ == "__main__":
    main()
