"""Prepare provisional v783 root-ID provenance for the manual-check cells."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np

if not __package__:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from flyai.screen_ocellar import candidate_labels
from flyai.validate_raw import verify_manifest


def packet_rows(audit: dict, annotations: Path, proofread: Path) -> list[dict]:
    expected: dict[int, tuple[str, str]] = {}
    for pair in audit["checks"]:
        for position in ("pre", "post"):
            root_id = int(pair[f"{position}_root_id"])
            role_side = (pair[f"{position}_role"], pair[f"{position}_side"])
            if root_id in expected and expected[root_id] != role_side:
                raise ValueError(f"Conflicting worksheet labels for root ID {root_id}")
            expected[root_id] = role_side
    labels = candidate_labels(annotations)
    proofread_ids = np.load(proofread, mmap_mode="r", allow_pickle=False)
    if proofread_ids.ndim != 1 or proofread_ids.dtype != np.uint64:
        raise ValueError("Expected one-dimensional uint64 proofread IDs")
    membership = set(map(int, proofread_ids[np.isin(proofread_ids, list(expected))]))
    found: dict[int, dict] = {}
    with annotations.open("r", encoding="utf-8-sig", newline="") as stream:
        reader = csv.DictReader(stream, delimiter="\t")
        required = {"root_id", "cell_type", "hemibrain_type", "side", "status",
                    "pos_x", "pos_y", "pos_z"}
        if not reader.fieldnames or not required.issubset(reader.fieldnames):
            raise ValueError("Annotation TSV lacks ID-packet fields")
        for row in reader:
            root_id = int(row["root_id"])
            if root_id in expected:
                if root_id in found:
                    raise ValueError(f"Duplicate annotation root ID {root_id}")
                found[root_id] = row
    if set(found) != set(expected) or not set(expected).issubset(membership):
        raise ValueError("Candidate root ID missing from annotations or proofread list")
    output = []
    for root_id in sorted(expected):
        row = found[root_id]
        label = labels.get(root_id)
        if not label or (label["role"], label["side"]) != expected[root_id]:
            raise ValueError(f"Role/side mismatch for root ID {root_id}")
        output.append({
            "root_id": str(root_id), "role": label["role"], "side": label["side"],
            "status": label["status"], "cell_type": row["cell_type"] or "(blank)",
            "hemibrain_type": row["hemibrain_type"] or "(blank)",
            "position": ",".join(row[key] for key in ("pos_x", "pos_y", "pos_z")),
            "proofread_member": True,
        })
    return output


def render_packet(rows: list[dict], annotation_sha: str, proofread_sha: str) -> str:
    lines = [
        "# Provisional candidate root-ID packet",
        "",
        "Status: **exploratory P2 preparation; no circuit IDs selected or frozen**.",
        "These are the 19 unique IDs used by the ten P1 manual-check pairs. The",
        "pinned annotation tag is `v2.1.0` for FAFB v783. Each ID was found in",
        "that TSV and the pinned proofread-root array; role and side matched the",
        "manual-check worksheet. This checks provenance, not physiological function.",
        "",
        f"Annotation SHA-256: `{annotation_sha}`.",
        f"Proofread-ID SHA-256: `{proofread_sha}`.",
        "Generated by `src/flyai/prepare_id_packet.py` from",
        "`data/derived/manual_pair_raw_audit.json` and pinned raw files.",
        "",
        "| Root ID | Candidate role | Side | Status | `cell_type` | `hemibrain_type` | Annotation position (x,y,z) |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row[key] for key in (
            "root_id", "role", "side", "status", "cell_type", "hemibrain_type", "position")) + " |")
    lines.extend([
        "",
        "DNp20 and DNp28 are identified by `hemibrain_type`; DNp22 by `cell_type`.",
        "The right DNp28 status is `outlier_seg`, a segmentation-issue flag.",
        "The 3D preview and these labels cannot resolve that flag. Signed-in",
        "connection reconciliation, graph rules, and sensor/motor mapping remain open.",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.workspace.resolve()
    manifest = verify_manifest(root, root / "data/raw/manifest.csv", {
        "proofread_connections_783.feather", "proofread_root_ids_783.npy",
        "per_neuron_neuropil_count_pre_783.feather",
        "Supplemental_file1_neuron_annotations_v2.1.0.tsv",
    })
    audit = json.loads((root / "data/derived/manual_pair_raw_audit.json").read_text(encoding="utf-8"))
    if audit["portal_verified"] or audit["raw_sha256"] != manifest["proofread_connections_783.feather"]["sha256"]:
        raise ValueError("Candidate audit does not match the pinned pending data")
    rows = packet_rows(audit, root / "data/raw/Supplemental_file1_neuron_annotations_v2.1.0.tsv",
                       root / "data/raw/proofread_root_ids_783.npy")
    output = root / "docs/candidate_id_packet.md"
    with output.open("x", encoding="utf-8") as stream:
        stream.write(render_packet(rows,
                                   manifest["Supplemental_file1_neuron_annotations_v2.1.0.tsv"]["sha256"],
                                   manifest["proofread_root_ids_783.npy"]["sha256"]))
    print(json.dumps({"output": str(output), "unique_ids": len(rows), "status": "provisional"}))


if __name__ == "__main__":
    main()
